### ISSUE TITLE
Android IoPay stucks on ioTex native voting

### ISSUE THREAD

**Issue by Tabjones** [iotexproject/iotex-explorer#1248] opened 2020-02-15 08:21 UTC
Hello, I think I found a bug on the Android app version 0.4.4(388) I would like to report:

I followed the instructions provided [here](https://medium.com/@iotex/staking-native-iotx-with-iopay-d3ca194b38ba):

- I have some native (non ERC-20) IOTX tokens in my app wallet, I want to stake them and vote for a delegate.

- When I reach the page "You are about to process ..." I click on Yes, a popup for confirmation appears, I approve that, but the app stucks on loading forever without ever resolving. 

- If I touch anything on the screen the loading overlay disappears and no staking has been done, nor I see any transaction history.

- This repeats over and over again no matter what I do, I tried waiting for hours, but the app is clearly stuck

I'm not sure how to proceed, any help is appreciated. thank you

**Comment by puncsky** [comment] 2020-02-18 23:33
Thank you for reporting this issue.

Please try [iopay desktop](https://iopay.iotex.io/desktop/) for the immediate access. To investigate the Android compatibility issue, we kindly request some more information from you:

* Manufacturer: e.g. samsung
* Model: e.g. Mi A2

**Comment by Tabjones** [comment] 2020-02-18 23:41
- Manufacturer: Blackview
- Model: P2 Lite
- Android version: 7.0
- Android security patch: 5 May 2017
- Kernel: 3.18.35+
- Build number: P2_Lite_Blackview_20170622

@puncsky thanks for replying, unfortunately, I cannot try iopay desktop because I cannot access my private key on the app wallet. The app freezes as described above also when trying to view my private key. Also, funds withdrawal freezes the same way, so I'm effectively locked out of my funds...
Please kindly tell me an alternative way of retrieving my private key, or provide an app update that doesnt freeze! thanks

**Comment by hunglmtb** [comment] 2020-02-19 03:59
@Tabjones Thank for your information
It seems your wallet could not be unlocked to do some actions.
Could you create another wallet, then view its private key on your phone?
Thanks

**Comment by Tabjones** [comment] 2020-02-19 06:39
@puncsky I can create another wallet, but I cannot see its private key, app hangs the same way as the first wallet.

**Comment by hunglmtb** [comment] 2020-02-19 17:23
we may need to build debug apk for @Tabjones ' phone to investigate what issue.
How do you think? @puncsky

**Comment by hunglmtb** [comment] 2020-02-20 10:16
Hi @Tabjones
We could not reproduce this on the devices we have. Your help is useful to check it out.
Could you help with checking this issue on debugging apk I'll send to your email the latest android iopay version includes some logs and toast of text?

**Comment by Tabjones** [comment] 2020-02-20 10:23
Hi @hunglmtb 
Sure, please send it and instruct me on what to do and how to read logs or whatever else you need.

**Comment by hunglmtb** [comment] 2020-02-20 10:34
@Tabjones Thank you. Let me prepare

**Comment by Tabjones** [comment] 2020-02-22 16:26
any news?

**Comment by hunglmtb** [comment] 2020-02-23 05:40
@Tabjones I sent to your email fspinelli@gmail.com. Could you take a loo

**Comment by Tabjones** [comment] 2020-02-23 08:46
@hunglmtb ok, sorry your mail was sent to the spam by google, so I didn't see it at first! I'll check it out

**Comment by Tabjones** [comment] 2020-02-23 13:38
@hunglmtb I installed the debug app. It seems like it is working. I get some "getAccountByWallet" messages with an address and success messages. this appears when I try to show my private key. Didnt try the voting because I dont have any funds. With the fact that this version is working for me is it possible to update the playstore app and try to retrieve my locked out funds on the other app?

**Comment by hunglmtb** [comment] 2020-02-23 17:47
On Sun, 23 Feb 2020 at 15:25, hung le <hung@iotex.io> wrote:
Thank for your checkingThat means you can view your private key?
If yes, there are some configurations between release and debug version so it couldn't decode account. We need more debug to find which cause the problem, then release an update one. I will ask some checking on your mobile next some days.Thanks for your help

-----------

On Sun, Feb 23, 2020, 9:35 PM Federico Spinelli <fspinelli@gmail.com> wrote:
Ok, thank you. Yes I can see my private key. But It might not just be configurations between builds. My release playstore version is v0.4.4(388), while the debug you gave me is INTERNAL_BUILD(392)
Looks like you are missing some versions on playstore.

------------

On Sun, 23 Feb 2020 at 15:44, hung le <hung@iotex.io> wrote:
There's a apk version here https://iopay.iotex.io/Could you install apk release one and  view private key on temporary account like debug one?Ps: apk version will not overwrite play store one on the phone
On Sun, Feb 23, 2020, 9:39 PM hung le <hung@iotex.io> wrote:
Thank for your info. Let's check it out 

------------

On Mon, Feb 24, 2020, 12:21 AM Federico Spinelli <fspinelli@gmail.com> wrote:
I've already checked the apk from your website some days ago, I can see the private key with that, but I was unable to vote the app was freezing.

----------

On Mon, Feb 24, 2020 at 12:37 AM hung le <hung@iotex.io> wrote:
Got it. Nevermind vote on apk version.To check it out, we will release an update version on play store and you will update and do some actions such as: view private key or stake, vote... Of course, it still not work but will log exceptions running time. We will see what happens with your device and release a patch for this issue and send you a notification of this update when it's ready. Pls feel free if you have any suggestionThanks

**Comment by Tabjones** [comment] 2020-02-23 20:18
ok, thank you, I will wait for it

**Comment by Tabjones** [comment] 2020-02-29 19:59
any news? I didn't get any update on playstore

**Comment by puncsky** [comment] 2020-03-31 03:45
let me ask @hunglmtb

**Comment by hunglmtb** [comment] 2020-03-31 07:06
@Tabjones v0.4.9 is ready on google play. Could you update then try?

**Comment by puncsky** [comment] 2020-04-01 00:55
closing for now unless there is negative feedback

**Closed by puncsky** 2020-04-01 00:55 UTC
