### ISSUE TITLE
Issue on swapping IOTX to IOTX-E

### ISSUE THREAD

**Issue by cryPT-BR** [iotexproject/iotex-explorer#1060] opened 2019-10-07 00:35 UTC
Hi everyone,

I've been trying to swap native IOTX to IOTX-E using the online tool but I keep getting the following message: "_failed to execute contract: TypeError: e.toLowerCase is not a function_". 

I'm using the most updated version of IoPay and I still can't finish the transaction.

Please help me out. Thanks!

**Comment by puncsky** [comment] 2019-10-07 23:14
https://github.com/iotexproject/web-bp/blob/e2e2b941b80ae126334cf531f5d566d49ea7c053/src/shared/profile/moveto-ethwallet.js#L337

**Comment by cryPT-BR** [comment] 2019-10-07 23:17
thanks but I can't see anything = 404 page not found error

**Comment by puncsky** [comment] 2019-10-07 23:22
sorry, that code reference is for our internal debugging purpose...

somehow I cannot reproduce the issue. what is the exact version number of your wallet? @cryPT-BR

**Comment by cryPT-BR** [comment] 2019-10-07 23:24
> sorry, that code reference is for our internal debugging purpose...
> 
> somehow I cannot reproduce the issue. what is the exact version number of your wallet? @cryPT-BR

I'm using the 0.6.1 version which I've downloaded twice just in case

**Comment by cryPT-BR** [comment] 2019-10-07 23:54
@puncsky By the way, what would be this address: 
**Mapping ETH Address**
0xf19185e3c89935b1224301d46f555979d3ad24cb

I noted the error takes place when I change the default option (Current ETH Address: 0xf19185e3c89935b1224301d46f555979d3ad24cb) to the 'Another ETH address' option, where I put my Atomic Wallet address. 
Sorry if I've been doing something wrong but this is the first time I make this kind of transaction

**Comment by nmhung1210** [comment] 2019-10-17 08:18
Closed in favor of https://github.com/iotexproject/web-bp/issues/1384

**Closed by nmhung1210** 2019-10-17 08:18 UTC
