### ISSUE TITLE
[windows][wallet]transication amount is inconsisit with request 

### ISSUE THREAD

**Issue by sxlwar** [iotexproject/iotex-explorer#1135] opened 2019-11-08 03:41 UTC
reproduce steps:

1. open [member.iotext.io](https://member.iotext.io), go to tools----> swap to IOTX-E
2. Select ‘other eth Address ' after entering the appropriate content on the page.
![image](https://user-images.githubusercontent.com/20088392/68447501-279a0800-021b-11ea-8de7-c59c236bb7aa.png)
3. click buttons  to continue until confirm Pop-ups appears in ioPay 
4. cancel the transaction, modify the transaction amount and then re-initiate the transaction.

the amount is still the old one

this problem only exists in windows

ioPay version: 0.6.3

**Comment by nmhung1210** [comment] 2019-11-29 02:11
I had to install `Window 10 Pro 10.0.18362.476` to perform the test and this issue could not be reproduced. Could you please provide information regarding the window version this issue happens?

**Comment by sxlwar** [comment] 2019-12-03 03:25
windows 10 version 1903(OS inner version 18362.476)

**Comment by nmhung1210** [comment] 2019-12-09 04:59
I'm still not able to reproduce this issue by following reproduce steps above. Temporary close this issue due to could not reproduce.

**Closed by nmhung1210** 2019-12-09 04:59 UTC
Labels: bug, electron, wallet
