### ISSUE TITLE
Wallet release 0.3.2 not opening on MacOS

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-explorer#720] opened 2019-06-16 14:15 UTC
Just downloaded the latest 0.3.2 release of the desktop wallet for Mac (both dmg & zip files) and it cannot be open, due to the following error: 

"Unable to open iotex-wallet because Apple cannot verify if it contains any malware. 
The software must be updated. For more informations, please contact the developer."

<img width="460" alt="Schermata 2019-06-15 alle 23 09 47" src="https://user-images.githubusercontent.com/11096047/59565287-b8482f80-9051-11e9-9f35-3006490f6ba5.png">

macOS 10.14.5 Mojave

**Comment by guo** [comment] 2019-06-16 15:13
It may not be signed properly. cc. @puncsky

**Comment by puncsky** [comment] 2019-06-16 20:47
I cannot reproduce it on my Mac. Could you provide an English version of the error message?

**Comment by puncsky** [comment] 2019-06-18 04:15
> Beginning in macOS 10.14.5, all new or updated kernel extensions and all software from developers new to distributing with Developer ID must be notarized in order to run. In a future version of macOS, notarization will be required by default for all software.

related to https://github.com/electron-userland/electron-builder/issues/3383

**Comment by raullenchai** [comment] 2019-06-19 04:41
https://github.com/electron-userland/electron-builder/issues/3383#issuecomment-493631040 says it is implemented in electron side. Should we retry?

**Comment by simonerom** [comment] 2019-06-19 20:37
To be honest I don't know where that message is coming from: I did try wallet 0.2.1 in the past and it worked, then downloaded 0.3 and got this message. Back to 0.2.1 and getting the same message, hence this must be related to the MacOS upgrade that happened in between
I searched the Internet for that message but did not find much (must be something new)
Making it short, macOS is saying "I won't open this app because I can't check if it contains any malwares"
I think you should be able to reproduce it on macOS  10.14.5 Mojave

**Comment by simonerom** [comment] 2019-08-06 17:26
FYI (Workaround found)
While this issue is still present (i.e. the wallet is not usable on any Mac with MacOS Mojave 10.14.x, I found this workaround: just Ctrl+Click on the app then click "Open" in the warning dialog. This will bypass the security check and add the app to the exceptions list.

Source: https://support.apple.com/en-gb/guide/mac-help/mh40617/10.14/mac/10.14

**Comment by puncsky** [comment] 2019-11-04 08:33
fixed in https://github.com/iotexproject/iotex-explorer/commit/a5016e0e3368f3f35162ac1ba9929fc218527fbf

**Closed by puncsky** 2019-11-04 08:33 UTC
