### ISSUE TITLE
Transaction not received 

### ISSUE THREAD

**Issue by Jdpedigo111** [iotexproject/iotex-explorer#1923] opened 2021-11-04 00:43 UTC
Hash-dc8b496e36178c62c2599d6c0cbac1712e5ff6374fd3a7d77663eeb351f1433e

receiving address-
 0x473974e3951e6cbD4c1D76Efc62553bff316066A
 
Never received shows completed

**Comment by mehmettugsat** [comment] 2021-11-04 16:57
same for me. What the hell is this? Also, any update?

**Comment by Jdpedigo111** [comment] 2021-11-04 17:45
No update from anyone. Contacted both platforms and both tell me to check with the other platform. I signed up on this cause this is who it was transferred through. It appears it's just lost. It looks like coinbase shows 2 different coins, CIOTX (Not tradable) IOTX (Crypto.com and Coinbase) 

Crypto says they are the same coin but clearly they aren't. I believe Crypto.com may have something wrong. So it appears I just lost everything I had and there's no way to track or to get it back

**Comment by mehmettugsat** [comment] 2021-11-04 18:26
i guess that you made wrong chose about network. it may?

**Comment by Jdpedigo111** [comment] 2021-11-04 18:32
I'm guessing so, no one can explain or help. So not sure what I done wrong. All of my other withdrawals have worked fine. Crypto.com also had froze transactions on IOTX at the same time. So not sure what went wrong. 

Did you ever find anything out on yours?

**Comment by mehmettugsat** [comment] 2021-11-04 18:37
No way yet. Still looking for it.

**Comment by guillaume57** [comment] 2021-11-05 10:56
Hello

for my part sending from iopay wallet to coinbase I got this response from iotex

Unfortunately, if you sent from ioPay wallet directly to Coinbase,
the tokens have been sent to the same address, but on a different blockchain.
Since Coinbase uses Ethereum chain IOTX-E tokens, it expected you to deposit Ethereum based IOTX instead of native IOTX tokens. So you essentially sent tokens to the same address as your Coinbase displayed address, but on IoTeX blockchain, so unless Coinbase recovers these tokens for you, you cannot recover them

**Comment by Jdpedigo111** [comment] 2021-11-05 11:38
So more then likely I have done something similar also. I have been trying to contact coinbase but have not had any luck reaching a live agent. I have sent several email request but get the same automated email response. The phone number only works for card holders. Maybe if you find a different way to contact them you can share. If I get a response or come up with another way I will share as well. 

I'm hoping coinbase can track it and get it figured out.

**Comment by guillaume57** [comment] 2021-11-05 11:43
I contacted coinbase by email
I got a bad hash error return in my email
I try to reach them from email impossible to contact them for the moment

if i find a solution i will keep informed

**Comment by Jdpedigo111** [comment] 2021-11-05 12:09
That's the same as I am getting. The has was not correct. It's just a automated email response saying there are a few things not right and the hash being one of them. I don't think they can process screen shots. 

The has I got from the URL and from Crypto.com where the funds were transferred from.

**Comment by mehmettugsat** [comment] 2021-11-05 15:05
Oh, sorry for both of you guys. My problem is not same. I am already aware about your struggle. You both lost your coins, there is no other chance. But, my issue is that i tried to convert my native IOTX coins to ERC-20 IOTX coins. And my transactions have been confirmed. But, there is still no any coins reached to my ETH wallet.

**Comment by Jdpedigo111** [comment] 2021-11-05 20:52
I finally was able to get someone from coinbase to respond to one of my email requests and several were sent. Kept sending email requests and in the message explained no one would respond besides a automated response telling me the hash was incorrect, as well as responding to every automated email response. Finally a response!!

Response from coinbase was, The transaction was performed using a network coinbase does not support, even this it was IOTX to IOtX the network used was not supported, therefore the coins are not recoverable. Basically lost all my coins. Lesson learned I guess. Just sucks to have lost all that money and their is no way to recover.

**Comment by jrynkiew** [comment] 2021-11-21 11:41
Hi,

Sorry, but none of the issues here relate to iotex-explorer directly, but rather in one case I see an ioTube issue, and in others it is sending tokens to the wrong chian. Also, please in the future create a seperate issue for your sepcific case, as it is impossible to help everyone in one github issue report.

Since the issues described here are not with iotex-explorer, but most likely you sending the tokens to the wrong chain, or pending ioTube cross-chain transfers, I am closing this issue. If you need support on this matter, please contact support@iotex.io by e-mail.

**Closed by jrynkiew** 2021-11-21 11:41 UTC
